import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/layout/header";
import cx from 'clsx';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: {template: '%s | Bitfa', default: 'Bifta'},
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={cx(inter.className, 'flex flex-col')}>
        <Header/>
        <main className="flex-1 overflow-auto">
            {children}
        </main>
        </body>
        </html>
    );
}
